### PR TITLE
Flags were broken

### PR DESCRIPTION
**Pull request by baderbuddy**
Fixes command line flags. I had pulled this out to remove the kubeconfig and master flags, but it looks like it broke all of the other flags.

### CODE REVIEW

**Comment by rbren** [comment]
I'd been meaning to take a look at this actually - I think `version` is broken too?

Would adding an `--org` flag to obviate the need for fairwinds-insights.yaml?

**Comment by baderbuddy** [comment]
Not counting the edge case of hostname yeah an --org would kill the need for the config. Want me to just go ahead and get that in?

**Comment by baderbuddy** [comment]
That was actually a lot easier than I expected :) I'll test it out before merging though. I think version is working with 0.2, commit doesn't seem to get saved though. I'll take a quick look at that.

**Review by rbren — APPROVED** [review]
🎉

**Pull request merged**
